# Generated by Django 4.1.7 on 2023-03-09 06:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awc',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('beat_no', models.IntegerField()),
                ('population', models.BigIntegerField()),
                ('females', models.BigIntegerField()),
                ('males', models.BigIntegerField()),
                ('pregnant', models.BigIntegerField()),
                ('lactating', models.BigIntegerField()),
                ('regular', models.IntegerField()),
                ('yrs0_6', models.IntegerField()),
                ('yrs6_11', models.IntegerField()),
                ('yrs11_18', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('awc_id', models.IntegerField()),
            ],
            options={
                'db_table': 'awc1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AwcSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asid', models.BigIntegerField(unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('coverage', models.CharField(max_length=254)),
                ('state', models.CharField(max_length=254)),
                ('district', models.CharField(max_length=254)),
                ('division', models.CharField(max_length=254)),
                ('beat_no', models.BigIntegerField()),
                ('area_id', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'awcspecific',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aww',
            fields=[
                ('awwid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('age', models.BigIntegerField()),
                ('contact', models.CharField(max_length=254)),
                ('awc_id', models.IntegerField()),
            ],
            options={
                'db_table': 'aww',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseHolds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.BigIntegerField()),
                ('noofmembers', models.BigIntegerField()),
                ('children', models.BigIntegerField()),
                ('pregnant', models.BigIntegerField()),
                ('lactating', models.BigIntegerField()),
                ('yrs0_6', models.BigIntegerField()),
                ('yrs6_11', models.BigIntegerField()),
                ('yrs11_18', models.BigIntegerField()),
                ('males', models.BigIntegerField()),
                ('females', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('awc_id', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'households',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadWellPictureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='WellPics/noImage.jpg', null=True, upload_to='WellPics/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('well_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('radius', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=8, null=True)),
                ('lat', models.CharField(max_length=15)),
                ('lng', models.CharField(max_length=15)),
                ('date', models.DateField(null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('water_quality', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
